add docker-compose and second level of DOMAIN_EXTENSION
hacor/unifi-freeradius-ldap pull request #2
Opened 2019-08-15 16:11 UTC by nemmeviu

These changes allow the project to be used for domains that have more than one hierarchy in DNS, and add docker-compose structure.

2019-08-19 08:10 UTC, hacor requested changes
Thanks for the PR!
Seems good to me, only a few more changes concerning the documentation
If you have any questions, let me know!

2019-08-19 08:10 UTC, hacor commented on README.md
> +After certificates copy to `./certs`.
After copying the certificates to `./certs`

2019-08-19 08:10 UTC, hacor commented on README.md
> +then, change the variables values for your environment and:
Change the variable values for your environment and run the following command

2019-08-19 08:10 UTC, hacor commented on docker-compose.yml
> +    #image: haor/freeradius-google-ldap:latest
I will rebuild this container after merging the PR

2019-08-19 08:10 UTC, hacor commented on docker-compose.yml
> +    #image: haor/freeradius-google-ldap:latest
You can then uncomment this line

2019-08-19 08:10 UTC, hacor commented on docker-compose.yml
> +    # don't have second level support on BASE_DOMAIN
You can delete this comment, I will rebuild the container

2019-08-19 08:10 UTC, hacor commented on env/freeradius.env.sample
> +BASE_DOMAIN=example
Add a comment line here with something like:
`# When setting up domain example.com.br`

2019-08-19 08:10 UTC, hacor commented on env/freeradius.env.sample
> +ACCESS_ALLOWED_CIDR=ip.access.point
Add a comment line:
```
# Which IP range is allowed access to the freeradius controller. This should be the IP range of the access points talking to the freeradius container
ACCESS_ALLOWED_CIDR=192.168.1.0/24
```

2019-08-22 02:45 UTC, nemmeviu commented
Ok. I will create a new PR with all changes.
Thanks!!

2019-08-22 02:45 UTC, closed without merging